#include "SignatureNames.h"
#include <QHash>

namespace SignatureNames {

QString toFriendlyName(const QString& signature)
{
    static const QHash<QString, QString> names = {
        // Skyrim / shared signatures
        {QStringLiteral("AACT"), QStringLiteral("Action")},
        {QStringLiteral("ACHR"), QStringLiteral("Placed NPC")},
        {QStringLiteral("ACTI"), QStringLiteral("Activator")},
        {QStringLiteral("ADDN"), QStringLiteral("Addon Node")},
        {QStringLiteral("ALCH"), QStringLiteral("Ingestible")},
        {QStringLiteral("AMMO"), QStringLiteral("Ammunition")},
        {QStringLiteral("ANIO"), QStringLiteral("Animated Object")},
        {QStringLiteral("APPA"), QStringLiteral("Apparatus")},
        {QStringLiteral("ARMA"), QStringLiteral("Armor Addon")},
        {QStringLiteral("ARMO"), QStringLiteral("Armor")},
        {QStringLiteral("ARTO"), QStringLiteral("Art Object")},
        {QStringLiteral("ASPC"), QStringLiteral("Acoustic Space")},
        {QStringLiteral("ASTP"), QStringLiteral("Association Type")},
        {QStringLiteral("AVIF"), QStringLiteral("Actor Value Information")},
        {QStringLiteral("BOOK"), QStringLiteral("Book")},
        {QStringLiteral("BPTD"), QStringLiteral("Body Part Data")},
        {QStringLiteral("CAMS"), QStringLiteral("Camera Shot")},
        {QStringLiteral("CELL"), QStringLiteral("Cell")},
        {QStringLiteral("CLAS"), QStringLiteral("Class")},
        {QStringLiteral("CLFM"), QStringLiteral("Color")},
        {QStringLiteral("CLMT"), QStringLiteral("Climate")},
        {QStringLiteral("COBJ"), QStringLiteral("Constructible Object")},
        {QStringLiteral("COLL"), QStringLiteral("Collision Layer")},
        {QStringLiteral("CONT"), QStringLiteral("Container")},
        {QStringLiteral("CPTH"), QStringLiteral("Camera Path")},
        {QStringLiteral("CSTY"), QStringLiteral("Combat Style")},
        {QStringLiteral("DEBR"), QStringLiteral("Debris")},
        {QStringLiteral("DIAL"), QStringLiteral("Dialog Topic")},
        {QStringLiteral("DLBR"), QStringLiteral("Dialog Branch")},
        {QStringLiteral("DLVW"), QStringLiteral("Dialog View")},
        {QStringLiteral("DOBJ"), QStringLiteral("Default Object Manager")},
        {QStringLiteral("DOOR"), QStringLiteral("Door")},
        {QStringLiteral("DUAL"), QStringLiteral("Dual Cast Data")},
        {QStringLiteral("ECZN"), QStringLiteral("Encounter Zone")},
        {QStringLiteral("EFSH"), QStringLiteral("Effect Shader")},
        {QStringLiteral("ENCH"), QStringLiteral("Object Effect")},
        {QStringLiteral("EQUP"), QStringLiteral("Equip Type")},
        {QStringLiteral("EXPL"), QStringLiteral("Explosion")},
        {QStringLiteral("EYES"), QStringLiteral("Eyes")},
        {QStringLiteral("FACT"), QStringLiteral("Faction")},
        {QStringLiteral("FLOR"), QStringLiteral("Flora")},
        {QStringLiteral("FLST"), QStringLiteral("FormID List")},
        {QStringLiteral("FSTP"), QStringLiteral("Footstep")},
        {QStringLiteral("FSTS"), QStringLiteral("Footstep Set")},
        {QStringLiteral("FURN"), QStringLiteral("Furniture")},
        {QStringLiteral("GLOB"), QStringLiteral("Global")},
        {QStringLiteral("GMST"), QStringLiteral("Game Setting")},
        {QStringLiteral("GRAS"), QStringLiteral("Grass")},
        {QStringLiteral("HAIR"), QStringLiteral("Hair")},
        {QStringLiteral("HAZD"), QStringLiteral("Hazard")},
        {QStringLiteral("HDPT"), QStringLiteral("Head Part")},
        {QStringLiteral("IDLE"), QStringLiteral("Idle Animation")},
        {QStringLiteral("IDLM"), QStringLiteral("Idle Marker")},
        {QStringLiteral("IMAD"), QStringLiteral("Image Space Adapter")},
        {QStringLiteral("IMGS"), QStringLiteral("Image Space")},
        {QStringLiteral("INFO"), QStringLiteral("Dialog Response")},
        {QStringLiteral("INGR"), QStringLiteral("Ingredient")},
        {QStringLiteral("IPCT"), QStringLiteral("Impact")},
        {QStringLiteral("IPDS"), QStringLiteral("Impact Data Set")},
        {QStringLiteral("KEYM"), QStringLiteral("Key")},
        {QStringLiteral("KYWD"), QStringLiteral("Keyword")},
        {QStringLiteral("LAND"), QStringLiteral("Landscape")},
        {QStringLiteral("LCRT"), QStringLiteral("Location Reference Type")},
        {QStringLiteral("LCTN"), QStringLiteral("Location")},
        {QStringLiteral("LGTM"), QStringLiteral("Lighting Template")},
        {QStringLiteral("LIGH"), QStringLiteral("Light")},
        {QStringLiteral("LSCR"), QStringLiteral("Load Screen")},
        {QStringLiteral("LTEX"), QStringLiteral("Landscape Texture")},
        {QStringLiteral("LVLI"), QStringLiteral("Leveled Item")},
        {QStringLiteral("LVLN"), QStringLiteral("Leveled NPC")},
        {QStringLiteral("LVSP"), QStringLiteral("Leveled Spell")},
        {QStringLiteral("MATO"), QStringLiteral("Material Object")},
        {QStringLiteral("MATT"), QStringLiteral("Material Type")},
        {QStringLiteral("MESG"), QStringLiteral("Message")},
        {QStringLiteral("MGEF"), QStringLiteral("Magic Effect")},
        {QStringLiteral("MISC"), QStringLiteral("Misc. Item")},
        {QStringLiteral("MOVT"), QStringLiteral("Movement Type")},
        {QStringLiteral("MSTT"), QStringLiteral("Moveable Static")},
        {QStringLiteral("MUSC"), QStringLiteral("Music Type")},
        {QStringLiteral("MUST"), QStringLiteral("Music Track")},
        {QStringLiteral("NAVI"), QStringLiteral("Navigation Mesh Info Map")},
        {QStringLiteral("NAVM"), QStringLiteral("Navigation Mesh")},
        {QStringLiteral("NOTE"), QStringLiteral("Note")},
        {QStringLiteral("NPC_"), QStringLiteral("Non-Player Character (Actor)")},
        {QStringLiteral("OTFT"), QStringLiteral("Outfit")},
        {QStringLiteral("PACK"), QStringLiteral("Package")},
        {QStringLiteral("PERK"), QStringLiteral("Perk")},
        {QStringLiteral("PGRE"), QStringLiteral("Placed Grenade")},
        {QStringLiteral("PHZD"), QStringLiteral("Placed Hazard")},
        {QStringLiteral("PROJ"), QStringLiteral("Projectile")},
        {QStringLiteral("QUST"), QStringLiteral("Quest")},
        {QStringLiteral("RACE"), QStringLiteral("Race")},
        {QStringLiteral("REFR"), QStringLiteral("Placed Object")},
        {QStringLiteral("REGN"), QStringLiteral("Region")},
        {QStringLiteral("RELA"), QStringLiteral("Relationship")},
        {QStringLiteral("REVB"), QStringLiteral("Reverb Parameters")},
        {QStringLiteral("RFCT"), QStringLiteral("Visual Effect")},
        {QStringLiteral("SCEN"), QStringLiteral("Scene")},
        {QStringLiteral("SCPT"), QStringLiteral("Script")},
        {QStringLiteral("SCRL"), QStringLiteral("Scroll")},
        {QStringLiteral("SHOU"), QStringLiteral("Shout")},
        {QStringLiteral("SLGM"), QStringLiteral("Soul Gem")},
        {QStringLiteral("SMBN"), QStringLiteral("Story Manager Branch Node")},
        {QStringLiteral("SMEN"), QStringLiteral("Story Manager Event Node")},
        {QStringLiteral("SMQN"), QStringLiteral("Story Manager Quest Node")},
        {QStringLiteral("SNCT"), QStringLiteral("Sound Category")},
        {QStringLiteral("SNDR"), QStringLiteral("Sound Descriptor")},
        {QStringLiteral("SOPM"), QStringLiteral("Sound Output Model")},
        {QStringLiteral("SOUN"), QStringLiteral("Sound Marker")},
        {QStringLiteral("SPEL"), QStringLiteral("Spell")},
        {QStringLiteral("SPGD"), QStringLiteral("Shader Particle Geometry")},
        {QStringLiteral("STAT"), QStringLiteral("Static")},
        {QStringLiteral("TACT"), QStringLiteral("Talking Activator")},
        {QStringLiteral("TREE"), QStringLiteral("Tree")},
        {QStringLiteral("TXST"), QStringLiteral("Texture Set")},
        {QStringLiteral("VTYP"), QStringLiteral("Voice Type")},
        {QStringLiteral("WATR"), QStringLiteral("Water")},
        {QStringLiteral("WEAP"), QStringLiteral("Weapon")},
        {QStringLiteral("WOOP"), QStringLiteral("Word of Power")},
        {QStringLiteral("WRLD"), QStringLiteral("Worldspace")},
        {QStringLiteral("WTHR"), QStringLiteral("Weather")},
        // Common subrecord field signatures
        {QStringLiteral("EDID"), QStringLiteral("Editor ID")},
        {QStringLiteral("FULL"), QStringLiteral("Name")},
        {QStringLiteral("OBND"), QStringLiteral("Object Bounds")},
        {QStringLiteral("DATA"), QStringLiteral("Data")},
        {QStringLiteral("MODL"), QStringLiteral("Model")},
        {QStringLiteral("MODT"), QStringLiteral("Model Texture Data")},
        {QStringLiteral("MODS"), QStringLiteral("Model Alternate Textures")},
        {QStringLiteral("MODF"), QStringLiteral("Model Flags")},
        {QStringLiteral("DESC"), QStringLiteral("Description")},
        {QStringLiteral("KSIZ"), QStringLiteral("Keyword Count")},
        {QStringLiteral("KWDA"), QStringLiteral("Keywords")},
        {QStringLiteral("VMAD"), QStringLiteral("Virtual Machine Adapter")},
        {QStringLiteral("CTDA"), QStringLiteral("Condition")},
        {QStringLiteral("CIS1"), QStringLiteral("Condition Item String 1")},
        {QStringLiteral("CIS2"), QStringLiteral("Condition Item String 2")},
        {QStringLiteral("CNAM"), QStringLiteral("Color")},
        {QStringLiteral("DNAM"), QStringLiteral("Data")},
        {QStringLiteral("ENAM"), QStringLiteral("Effect")},
        {QStringLiteral("FNAM"), QStringLiteral("Flags")},
        {QStringLiteral("GNAM"), QStringLiteral("Data")},
        {QStringLiteral("HNAM"), QStringLiteral("Data")},
        {QStringLiteral("INAM"), QStringLiteral("Data")},
        {QStringLiteral("JNAM"), QStringLiteral("Data")},
        {QStringLiteral("KNAM"), QStringLiteral("Data")},
        {QStringLiteral("LNAM"), QStringLiteral("Data")},
        {QStringLiteral("MNAM"), QStringLiteral("Data")},
        {QStringLiteral("NNAM"), QStringLiteral("Data")},
        {QStringLiteral("ONAM"), QStringLiteral("Data")},
        {QStringLiteral("PNAM"), QStringLiteral("Data")},
        {QStringLiteral("QNAM"), QStringLiteral("Data")},
        {QStringLiteral("RNAM"), QStringLiteral("Data")},
        {QStringLiteral("SNAM"), QStringLiteral("Sound")},
        {QStringLiteral("TNAM"), QStringLiteral("Data")},
        {QStringLiteral("UNAM"), QStringLiteral("Data")},
        {QStringLiteral("VNAM"), QStringLiteral("Data")},
        {QStringLiteral("WNAM"), QStringLiteral("Data")},
        {QStringLiteral("XNAM"), QStringLiteral("Data")},
        {QStringLiteral("YNAM"), QStringLiteral("Pick Up Sound")},
        {QStringLiteral("ZNAM"), QStringLiteral("Put Down Sound")},
        {QStringLiteral("ANAM"), QStringLiteral("Data")},
        {QStringLiteral("BNAM"), QStringLiteral("Data")},
        {QStringLiteral("SCRI"), QStringLiteral("Script")},
        {QStringLiteral("SCHR"), QStringLiteral("Script Data")},
        {QStringLiteral("SCTX"), QStringLiteral("Script Source")},
        {QStringLiteral("SCDA"), QStringLiteral("Compiled Script Data")},
        {QStringLiteral("SLSD"), QStringLiteral("Local Variable Data")},
        {QStringLiteral("SCVR"), QStringLiteral("Variable Name")},
        {QStringLiteral("SCRV"), QStringLiteral("Variable Reference")},
        {QStringLiteral("SCRO"), QStringLiteral("Object Reference")},
        {QStringLiteral("ICON"), QStringLiteral("Large Icon")},
        {QStringLiteral("MICO"), QStringLiteral("Small Icon")},
        {QStringLiteral("ICO2"), QStringLiteral("Large Icon (female)")},
        {QStringLiteral("MIC2"), QStringLiteral("Small Icon (female)")},
        {QStringLiteral("EITM"), QStringLiteral("Object Effect")},
        {QStringLiteral("ETYP"), QStringLiteral("Equipment Type")},
        {QStringLiteral("BIDS"), QStringLiteral("Block Bash Impact Data Set")},
        {QStringLiteral("BAMT"), QStringLiteral("Alternate Block Material")},
        {QStringLiteral("BODT"), QStringLiteral("Body Template")},
        {QStringLiteral("BOD2"), QStringLiteral("Biped Body Template")},
        {QStringLiteral("DEST"), QStringLiteral("Destructible Header")},
        {QStringLiteral("DSTD"), QStringLiteral("Destruction Stage Data")},
        {QStringLiteral("DSTF"), QStringLiteral("Destruction Stage End Marker")},
        {QStringLiteral("DMDL"), QStringLiteral("Destruction Model")},
        {QStringLiteral("DMDT"), QStringLiteral("Destruction Model Texture Data")},
        {QStringLiteral("DMDS"), QStringLiteral("Destruction Model Alternate Textures")},
        {QStringLiteral("EFID"), QStringLiteral("Effect FormID")},
        {QStringLiteral("EFIT"), QStringLiteral("Effect Data")},
        {QStringLiteral("ENIT"), QStringLiteral("Effect Data")},
        {QStringLiteral("CNTO"), QStringLiteral("Item")},
        {QStringLiteral("COCT"), QStringLiteral("Item Count")},
        {QStringLiteral("COED"), QStringLiteral("Extra Data")},
        {QStringLiteral("LVLO"), QStringLiteral("Leveled List Entry")},
        {QStringLiteral("LLCT"), QStringLiteral("Count")},
        {QStringLiteral("LVLF"), QStringLiteral("Flags")},
        {QStringLiteral("LVLG"), QStringLiteral("Global")},
        {QStringLiteral("XCNT"), QStringLiteral("Count")},
        {QStringLiteral("XLOC"), QStringLiteral("Lock")},
        {QStringLiteral("XOWN"), QStringLiteral("Owner")},
        {QStringLiteral("XRNK"), QStringLiteral("Rank")},
        {QStringLiteral("XESP"), QStringLiteral("Enable Parent")},
        {QStringLiteral("XTEL"), QStringLiteral("Teleport Destination")},
        {QStringLiteral("XSCL"), QStringLiteral("Scale")},
        {QStringLiteral("XLCM"), QStringLiteral("Level Modifier")},
        {QStringLiteral("XLCN"), QStringLiteral("Persistent Location")},
        {QStringLiteral("XLRT"), QStringLiteral("Location Reference Type")},
        {QStringLiteral("XMRK"), QStringLiteral("Map Marker")},
        {QStringLiteral("XPRD"), QStringLiteral("Patrol Data")},
        {QStringLiteral("XPPA"), QStringLiteral("Patrol Idle")},
        {QStringLiteral("INAM"), QStringLiteral("Idle")},
        {QStringLiteral("XRGD"), QStringLiteral("Ragdoll Data")},
        {QStringLiteral("XRGB"), QStringLiteral("Ragdoll Biped Data")},
        {QStringLiteral("XPCI"), QStringLiteral("Charge")},
        {QStringLiteral("XLKR"), QStringLiteral("Linked Reference")},
        {QStringLiteral("XAPD"), QStringLiteral("Activate Parents Flags")},
        {QStringLiteral("XAPR"), QStringLiteral("Activate Parent Ref")},
        {QStringLiteral("XEMI"), QStringLiteral("Emittance")},
        {QStringLiteral("XMBR"), QStringLiteral("Multi-Bound Reference")},
        {QStringLiteral("XPRM"), QStringLiteral("Primitive")},
        {QStringLiteral("NAME"), QStringLiteral("Base")},
        {QStringLiteral("XNDP"), QStringLiteral("Navigation Door Link")},
        {QStringLiteral("XPOD"), QStringLiteral("Portal")},
        {QStringLiteral("XPTL"), QStringLiteral("Portal Data")},
        {QStringLiteral("XRMR"), QStringLiteral("Room Data Header")},
        {QStringLiteral("XLRM"), QStringLiteral("Linked Room")},
        {QStringLiteral("XOCP"), QStringLiteral("Occlusion Plane Data")},
        {QStringLiteral("XORD"), QStringLiteral("Linked Occlusion Planes")},
        {QStringLiteral("XMBP"), QStringLiteral("Multi-Bound Primitive Marker")},
        {QStringLiteral("XWCN"), QStringLiteral("Water Current Zone Data Count")},
        {QStringLiteral("XWCU"), QStringLiteral("Water Current Zone Data")},
        {QStringLiteral("XCVL"), QStringLiteral("Water Velocity")},
        {QStringLiteral("XCZC"), QStringLiteral("Current Zone Cell")},
        {QStringLiteral("XCZA"), QStringLiteral("Current Zone")},
        {QStringLiteral("XHTW"), QStringLiteral("Head Tracking Weight")},
        {QStringLiteral("XFVC"), QStringLiteral("Favor Cost")},
        {QStringLiteral("XEZN"), QStringLiteral("Encounter Zone")},
        {QStringLiteral("XILL"), QStringLiteral("Illness")},
        {QStringLiteral("XIS2"), QStringLiteral("Ignored by Sandbox")},
        {QStringLiteral("XLRL"), QStringLiteral("Location Reference")},
        {QStringLiteral("XHOR"), QStringLiteral("Horse")},
        {QStringLiteral("XACT"), QStringLiteral("Action Flag")},
        {QStringLiteral("XCLP"), QStringLiteral("Linked Reference Color")},
        {QStringLiteral("XCWT"), QStringLiteral("Water Type")},
        {QStringLiteral("XCLW"), QStringLiteral("Water Height")},
        {QStringLiteral("XCAS"), QStringLiteral("Acoustic Space")},
        {QStringLiteral("XCIM"), QStringLiteral("Image Space")},
        {QStringLiteral("XCCM"), QStringLiteral("Sky/Weather from Region")},
        {QStringLiteral("XCET"), QStringLiteral("Cell Encounter Type")},
        {QStringLiteral("XCLR"), QStringLiteral("Regions")},
        {QStringLiteral("XCLL"), QStringLiteral("Lighting")},
        {QStringLiteral("XCMO"), QStringLiteral("Music Type")},
        {QStringLiteral("XWEM"), QStringLiteral("Water Environment Map")},
        {QStringLiteral("XILS"), QStringLiteral("Interior LOD")},
        {QStringLiteral("TVDT"), QStringLiteral("Occlusion Data")},
        {QStringLiteral("MHDT"), QStringLiteral("Max Height Data")},
        {QStringLiteral("LTMP"), QStringLiteral("Lighting Template")},
        {QStringLiteral("LNAM"), QStringLiteral("Water Lighting")},
        {QStringLiteral("XNAM"), QStringLiteral("Water Noise Texture")},
        {QStringLiteral("INTV"), QStringLiteral("Interval")},
        {QStringLiteral("NAM0"), QStringLiteral("Data")},
        {QStringLiteral("NAM1"), QStringLiteral("Data")},
        {QStringLiteral("NAM2"), QStringLiteral("Data")},
        {QStringLiteral("NAM3"), QStringLiteral("Data")},
        {QStringLiteral("NAM4"), QStringLiteral("Data")},
        {QStringLiteral("NAM5"), QStringLiteral("Data")},
        {QStringLiteral("NAM6"), QStringLiteral("Data")},
        {QStringLiteral("NAM7"), QStringLiteral("Data")},
        {QStringLiteral("NAM8"), QStringLiteral("Data")},
        {QStringLiteral("NAM9"), QStringLiteral("Data")},
        {QStringLiteral("MOD2"), QStringLiteral("Model")},
        {QStringLiteral("MOD3"), QStringLiteral("Model")},
        {QStringLiteral("MOD4"), QStringLiteral("Model")},
        {QStringLiteral("MOD5"), QStringLiteral("Model")},
        {QStringLiteral("MO2T"), QStringLiteral("Model Texture Data")},
        {QStringLiteral("MO3T"), QStringLiteral("Model Texture Data")},
        {QStringLiteral("MO4T"), QStringLiteral("Model Texture Data")},
        {QStringLiteral("MO5T"), QStringLiteral("Model Texture Data")},
        {QStringLiteral("MO2S"), QStringLiteral("Model Alternate Textures")},
        {QStringLiteral("MO3S"), QStringLiteral("Model Alternate Textures")},
        {QStringLiteral("MO4S"), QStringLiteral("Model Alternate Textures")},
        {QStringLiteral("MO5S"), QStringLiteral("Model Alternate Textures")},
        {QStringLiteral("RDAT"), QStringLiteral("Data Entry")},
        {QStringLiteral("RDOT"), QStringLiteral("Object")},
        {QStringLiteral("RDWT"), QStringLiteral("Weather")},
        {QStringLiteral("RDMP"), QStringLiteral("Map Name")},
        {QStringLiteral("RDGS"), QStringLiteral("Grasses")},
        {QStringLiteral("RDMD"), QStringLiteral("Music")},
        {QStringLiteral("RDSA"), QStringLiteral("Sounds")},
        {QStringLiteral("WLST"), QStringLiteral("Weather List")},
        {QStringLiteral("DALC"), QStringLiteral("Directional Ambient Lighting Colors")},
        {QStringLiteral("MODQ"), QStringLiteral("Model Texture Data")},
        {QStringLiteral("SNDD"), QStringLiteral("Sound Data")},
        {QStringLiteral("AIDT"), QStringLiteral("AI Data")},
        {QStringLiteral("PKID"), QStringLiteral("Package")},
        {QStringLiteral("SPLO"), QStringLiteral("Actor Effect")},
        {QStringLiteral("ACBS"), QStringLiteral("Configuration")},
        {QStringLiteral("RNAM"), QStringLiteral("Race")},
        {QStringLiteral("VTCK"), QStringLiteral("Voice")},
        {QStringLiteral("TPLT"), QStringLiteral("Template")},
        {QStringLiteral("WNAM"), QStringLiteral("Worn Armor")},
        {QStringLiteral("ANAM"), QStringLiteral("Far Away Model")},
        {QStringLiteral("ATKD"), QStringLiteral("Attack Data")},
        {QStringLiteral("ATKE"), QStringLiteral("Attack Event")},
        {QStringLiteral("ATKR"), QStringLiteral("Attack Race")},
        {QStringLiteral("DOFT"), QStringLiteral("Default Outfit")},
        {QStringLiteral("SOFT"), QStringLiteral("Sleep Outfit")},
        {QStringLiteral("DPLT"), QStringLiteral("Default Package List")},
        {QStringLiteral("CRIF"), QStringLiteral("Crime Faction")},
        {QStringLiteral("FTST"), QStringLiteral("Feature Set")},
        {QStringLiteral("HCLF"), QStringLiteral("Hair Color")},
        {QStringLiteral("PRKR"), QStringLiteral("Perk")},
        {QStringLiteral("PRKZ"), QStringLiteral("Perk Count")},
        {QStringLiteral("TINC"), QStringLiteral("Tint Index Color")},
        {QStringLiteral("TINI"), QStringLiteral("Tint Index")},
        {QStringLiteral("TIAS"), QStringLiteral("Tint Index Preset")},
        {QStringLiteral("TINV"), QStringLiteral("Tint Index Value")},
        {QStringLiteral("TIFC"), QStringLiteral("Tint Index Feature Count")},
        {QStringLiteral("SHRT"), QStringLiteral("Short Name")},
        {QStringLiteral("BPTN"), QStringLiteral("Part Name")},
        {QStringLiteral("BPNN"), QStringLiteral("Node Name")},
        {QStringLiteral("BPNT"), QStringLiteral("Part Node")},
        {QStringLiteral("BPND"), QStringLiteral("Body Part Data")},
        {QStringLiteral("BPNI"), QStringLiteral("Limb Replacement Model")},
        // NPC_ / Actor subrecords
        {QStringLiteral("NAM6"), QStringLiteral("Height")},
        {QStringLiteral("NAM7"), QStringLiteral("Weight")},
        {QStringLiteral("QSTI"), QStringLiteral("Quest")},
        {QStringLiteral("QSTR"), QStringLiteral("Quest")},
        {QStringLiteral("INDX"), QStringLiteral("Index")},
        {QStringLiteral("FLTR"), QStringLiteral("Filter")},
        {QStringLiteral("NIFZ"), QStringLiteral("Model Filenames")},
        {QStringLiteral("NIFT"), QStringLiteral("Model Textures")},
        {QStringLiteral("TX00"), QStringLiteral("Diffuse")},
        {QStringLiteral("TX01"), QStringLiteral("Normal/Gloss")},
        {QStringLiteral("TX02"), QStringLiteral("Environment Mask/Subsurface Tint")},
        {QStringLiteral("TX03"), QStringLiteral("Glow/Detail Map")},
        {QStringLiteral("TX04"), QStringLiteral("Height")},
        {QStringLiteral("TX05"), QStringLiteral("Environment")},
        {QStringLiteral("TX06"), QStringLiteral("Multilayer")},
        {QStringLiteral("TX07"), QStringLiteral("Backlight Mask/Specular")},
        {QStringLiteral("DODT"), QStringLiteral("Decal Data")},
        // Weapon subrecords
        {QStringLiteral("CRDT"), QStringLiteral("Critical Data")},
        {QStringLiteral("VNAM"), QStringLiteral("Detection Sound Level")},
        {QStringLiteral("NNAM"), QStringLiteral("Embedded Weapon Node")},
        {QStringLiteral("INAM"), QStringLiteral("Impact Data Set")},
        {QStringLiteral("WNAM"), QStringLiteral("1st Person Model Object")},
        {QStringLiteral("SNAM"), QStringLiteral("Attack Sound")},
        {QStringLiteral("TNAM"), QStringLiteral("Template")},
        // Armor subrecords
        {QStringLiteral("RNAM"), QStringLiteral("Race")},
        {QStringLiteral("ENAM"), QStringLiteral("Enchantment Charge")},
        {QStringLiteral("BNAM"), QStringLiteral("Bash Impact Data Set")},
        {QStringLiteral("CNAM"), QStringLiteral("Template Armor")},
        // Quest subrecords
        {QStringLiteral("ALST"), QStringLiteral("Alias Start")},
        {QStringLiteral("ALLS"), QStringLiteral("Alias Location Start")},
        {QStringLiteral("ALID"), QStringLiteral("Alias ID")},
        {QStringLiteral("ALDN"), QStringLiteral("Alias Display Name")},
        {QStringLiteral("ALFR"), QStringLiteral("Forced Reference")},
        {QStringLiteral("ALFE"), QStringLiteral("Forced to Equipment")},
        {QStringLiteral("ALFL"), QStringLiteral("Alias Flags")},
        {QStringLiteral("ALCO"), QStringLiteral("Alias Fill Conditions")},
        {QStringLiteral("ALEA"), QStringLiteral("Alias External Aliases")},
        {QStringLiteral("ALED"), QStringLiteral("Alias End")},
        {QStringLiteral("ALEK"), QStringLiteral("Alias Package Data")},
        {QStringLiteral("ALEQ"), QStringLiteral("Alias Equipment Type")},
        {QStringLiteral("ALFA"), QStringLiteral("Forced Into Alias")},
        {QStringLiteral("ALFC"), QStringLiteral("Alias Fill From Collection")},
        {QStringLiteral("ALFI"), QStringLiteral("Alias Forced Into Alias")},
        {QStringLiteral("ALRT"), QStringLiteral("Alias Reference Type")},
        {QStringLiteral("ALSP"), QStringLiteral("Alias Spells")},
        {QStringLiteral("ALUA"), QStringLiteral("Alias Unique Actor")},
        {QStringLiteral("NNAM"), QStringLiteral("Next Quest")},
        // Dialogue / INFO subrecords
        {QStringLiteral("TRDT"), QStringLiteral("Response Data")},
        {QStringLiteral("NAM1"), QStringLiteral("Response Text")},
        {QStringLiteral("NAM2"), QStringLiteral("Script Notes")},
        {QStringLiteral("NAM3"), QStringLiteral("Edits")},
        {QStringLiteral("TCLT"), QStringLiteral("Choice")},
        {QStringLiteral("TCLF"), QStringLiteral("Link From Topic")},
        {QStringLiteral("TWAT"), QStringLiteral("Walk Away Topic")},
        // Record header fields
        {QStringLiteral("Record Header"), QStringLiteral("")},

        // Fallout 4 / additional signatures
        {QStringLiteral("AECH"), QStringLiteral("Audio Effect Chain")},
        {QStringLiteral("AMDL"), QStringLiteral("Aim Model")},
        {QStringLiteral("BNDS"), QStringLiteral("Bendable Spline")},
        {QStringLiteral("DFOB"), QStringLiteral("Default Object")},
        {QStringLiteral("DMGT"), QStringLiteral("Damage Type")},
        {QStringLiteral("GDRY"), QStringLiteral("God Rays")},
        {QStringLiteral("INNR"), QStringLiteral("Instance Naming Rules")},
        {QStringLiteral("KSSM"), QStringLiteral("Sound Keyword Mapping")},
        {QStringLiteral("LAYR"), QStringLiteral("Layer")},
        {QStringLiteral("LENS"), QStringLiteral("Lens Flare")},
        {QStringLiteral("NOCM"), QStringLiteral("Navigation Mesh Obstacle Manager")},
        {QStringLiteral("OMOD"), QStringLiteral("Object Modification")},
        {QStringLiteral("PKIN"), QStringLiteral("Pack-In")},
        {QStringLiteral("RFGP"), QStringLiteral("Reference Group")},
        {QStringLiteral("SCCO"), QStringLiteral("Scene Collection")},
        {QStringLiteral("TERM"), QStringLiteral("Terminal")},
        {QStringLiteral("TRNS"), QStringLiteral("Transform")},
        {QStringLiteral("ZOOM"), QStringLiteral("Zoom")},
    };

    auto it = names.find(signature);
    if (it != names.end())
        return it.value();
    return signature;
}

} // namespace SignatureNames
