#include "SignatureNames.h"
#include <QHash>

namespace SignatureNames {

QString toFriendlyName(const QString& signature)
{
    static const QHash<QString, QString> names = {
        // Skyrim / shared signatures
        {QStringLiteral("AACT"), QStringLiteral("Action")},
        {QStringLiteral("ACHR"), QStringLiteral("Placed NPC")},
        {QStringLiteral("ACTI"), QStringLiteral("Activator")},
        {QStringLiteral("ADDN"), QStringLiteral("Addon Node")},
        {QStringLiteral("ALCH"), QStringLiteral("Ingestible")},
        {QStringLiteral("AMMO"), QStringLiteral("Ammunition")},
        {QStringLiteral("ANIO"), QStringLiteral("Animated Object")},
        {QStringLiteral("APPA"), QStringLiteral("Apparatus")},
        {QStringLiteral("ARMA"), QStringLiteral("Armor Addon")},
        {QStringLiteral("ARMO"), QStringLiteral("Armor")},
        {QStringLiteral("ARTO"), QStringLiteral("Art Object")},
        {QStringLiteral("ASPC"), QStringLiteral("Acoustic Space")},
        {QStringLiteral("ASTP"), QStringLiteral("Association Type")},
        {QStringLiteral("AVIF"), QStringLiteral("Actor Value Information")},
        {QStringLiteral("BOOK"), QStringLiteral("Book")},
        {QStringLiteral("BPTD"), QStringLiteral("Body Part Data")},
        {QStringLiteral("CAMS"), QStringLiteral("Camera Shot")},
        {QStringLiteral("CELL"), QStringLiteral("Cell")},
        {QStringLiteral("CLAS"), QStringLiteral("Class")},
        {QStringLiteral("CLFM"), QStringLiteral("Color")},
        {QStringLiteral("CLMT"), QStringLiteral("Climate")},
        {QStringLiteral("COBJ"), QStringLiteral("Constructible Object")},
        {QStringLiteral("COLL"), QStringLiteral("Collision Layer")},
        {QStringLiteral("CONT"), QStringLiteral("Container")},
        {QStringLiteral("CPTH"), QStringLiteral("Camera Path")},
        {QStringLiteral("CSTY"), QStringLiteral("Combat Style")},
        {QStringLiteral("DEBR"), QStringLiteral("Debris")},
        {QStringLiteral("DIAL"), QStringLiteral("Dialog Topic")},
        {QStringLiteral("DLBR"), QStringLiteral("Dialog Branch")},
        {QStringLiteral("DLVW"), QStringLiteral("Dialog View")},
        {QStringLiteral("DOBJ"), QStringLiteral("Default Object Manager")},
        {QStringLiteral("DOOR"), QStringLiteral("Door")},
        {QStringLiteral("DUAL"), QStringLiteral("Dual Cast Data")},
        {QStringLiteral("ECZN"), QStringLiteral("Encounter Zone")},
        {QStringLiteral("EFSH"), QStringLiteral("Effect Shader")},
        {QStringLiteral("ENCH"), QStringLiteral("Object Effect")},
        {QStringLiteral("EQUP"), QStringLiteral("Equip Type")},
        {QStringLiteral("EXPL"), QStringLiteral("Explosion")},
        {QStringLiteral("EYES"), QStringLiteral("Eyes")},
        {QStringLiteral("FACT"), QStringLiteral("Faction")},
        {QStringLiteral("FLOR"), QStringLiteral("Flora")},
        {QStringLiteral("FLST"), QStringLiteral("FormID List")},
        {QStringLiteral("FSTP"), QStringLiteral("Footstep")},
        {QStringLiteral("FSTS"), QStringLiteral("Footstep Set")},
        {QStringLiteral("FURN"), QStringLiteral("Furniture")},
        {QStringLiteral("GLOB"), QStringLiteral("Global")},
        {QStringLiteral("GMST"), QStringLiteral("Game Setting")},
        {QStringLiteral("GRAS"), QStringLiteral("Grass")},
        {QStringLiteral("HAIR"), QStringLiteral("Hair")},
        {QStringLiteral("HAZD"), QStringLiteral("Hazard")},
        {QStringLiteral("HDPT"), QStringLiteral("Head Part")},
        {QStringLiteral("IDLE"), QStringLiteral("Idle Animation")},
        {QStringLiteral("IDLM"), QStringLiteral("Idle Marker")},
        {QStringLiteral("IMAD"), QStringLiteral("Image Space Adapter")},
        {QStringLiteral("IMGS"), QStringLiteral("Image Space")},
        {QStringLiteral("INFO"), QStringLiteral("Dialog Response")},
        {QStringLiteral("INGR"), QStringLiteral("Ingredient")},
        {QStringLiteral("IPCT"), QStringLiteral("Impact")},
        {QStringLiteral("IPDS"), QStringLiteral("Impact Data Set")},
        {QStringLiteral("KEYM"), QStringLiteral("Key")},
        {QStringLiteral("KYWD"), QStringLiteral("Keyword")},
        {QStringLiteral("LAND"), QStringLiteral("Landscape")},
        {QStringLiteral("LCRT"), QStringLiteral("Location Reference Type")},
        {QStringLiteral("LCTN"), QStringLiteral("Location")},
        {QStringLiteral("LGTM"), QStringLiteral("Lighting Template")},
        {QStringLiteral("LIGH"), QStringLiteral("Light")},
        {QStringLiteral("LSCR"), QStringLiteral("Load Screen")},
        {QStringLiteral("LTEX"), QStringLiteral("Landscape Texture")},
        {QStringLiteral("LVLI"), QStringLiteral("Leveled Item")},
        {QStringLiteral("LVLN"), QStringLiteral("Leveled NPC")},
        {QStringLiteral("LVSP"), QStringLiteral("Leveled Spell")},
        {QStringLiteral("MATO"), QStringLiteral("Material Object")},
        {QStringLiteral("MATT"), QStringLiteral("Material Type")},
        {QStringLiteral("MESG"), QStringLiteral("Message")},
        {QStringLiteral("MGEF"), QStringLiteral("Magic Effect")},
        {QStringLiteral("MISC"), QStringLiteral("Misc. Item")},
        {QStringLiteral("MOVT"), QStringLiteral("Movement Type")},
        {QStringLiteral("MSTT"), QStringLiteral("Moveable Static")},
        {QStringLiteral("MUSC"), QStringLiteral("Music Type")},
        {QStringLiteral("MUST"), QStringLiteral("Music Track")},
        {QStringLiteral("NAVI"), QStringLiteral("Navigation Mesh Info Map")},
        {QStringLiteral("NAVM"), QStringLiteral("Navigation Mesh")},
        {QStringLiteral("NOTE"), QStringLiteral("Note")},
        {QStringLiteral("NPC_"), QStringLiteral("Non-Player Character (Actor)")},
        {QStringLiteral("OTFT"), QStringLiteral("Outfit")},
        {QStringLiteral("PACK"), QStringLiteral("Package")},
        {QStringLiteral("PERK"), QStringLiteral("Perk")},
        {QStringLiteral("PGRE"), QStringLiteral("Placed Grenade")},
        {QStringLiteral("PHZD"), QStringLiteral("Placed Hazard")},
        {QStringLiteral("PROJ"), QStringLiteral("Projectile")},
        {QStringLiteral("QUST"), QStringLiteral("Quest")},
        {QStringLiteral("RACE"), QStringLiteral("Race")},
        {QStringLiteral("REFR"), QStringLiteral("Placed Object")},
        {QStringLiteral("REGN"), QStringLiteral("Region")},
        {QStringLiteral("RELA"), QStringLiteral("Relationship")},
        {QStringLiteral("REVB"), QStringLiteral("Reverb Parameters")},
        {QStringLiteral("RFCT"), QStringLiteral("Visual Effect")},
        {QStringLiteral("SCEN"), QStringLiteral("Scene")},
        {QStringLiteral("SCPT"), QStringLiteral("Script")},
        {QStringLiteral("SCRL"), QStringLiteral("Scroll")},
        {QStringLiteral("SHOU"), QStringLiteral("Shout")},
        {QStringLiteral("SLGM"), QStringLiteral("Soul Gem")},
        {QStringLiteral("SMBN"), QStringLiteral("Story Manager Branch Node")},
        {QStringLiteral("SMEN"), QStringLiteral("Story Manager Event Node")},
        {QStringLiteral("SMQN"), QStringLiteral("Story Manager Quest Node")},
        {QStringLiteral("SNCT"), QStringLiteral("Sound Category")},
        {QStringLiteral("SNDR"), QStringLiteral("Sound Descriptor")},
        {QStringLiteral("SOPM"), QStringLiteral("Sound Output Model")},
        {QStringLiteral("SOUN"), QStringLiteral("Sound Marker")},
        {QStringLiteral("SPEL"), QStringLiteral("Spell")},
        {QStringLiteral("SPGD"), QStringLiteral("Shader Particle Geometry")},
        {QStringLiteral("STAT"), QStringLiteral("Static")},
        {QStringLiteral("TACT"), QStringLiteral("Talking Activator")},
        {QStringLiteral("TREE"), QStringLiteral("Tree")},
        {QStringLiteral("TXST"), QStringLiteral("Texture Set")},
        {QStringLiteral("VTYP"), QStringLiteral("Voice Type")},
        {QStringLiteral("WATR"), QStringLiteral("Water")},
        {QStringLiteral("WEAP"), QStringLiteral("Weapon")},
        {QStringLiteral("WOOP"), QStringLiteral("Word of Power")},
        {QStringLiteral("WRLD"), QStringLiteral("Worldspace")},
        {QStringLiteral("WTHR"), QStringLiteral("Weather")},
        // Fallout 4 / additional signatures
        {QStringLiteral("AECH"), QStringLiteral("Audio Effect Chain")},
        {QStringLiteral("AMDL"), QStringLiteral("Aim Model")},
        {QStringLiteral("BNDS"), QStringLiteral("Bendable Spline")},
        {QStringLiteral("DFOB"), QStringLiteral("Default Object")},
        {QStringLiteral("DMGT"), QStringLiteral("Damage Type")},
        {QStringLiteral("GDRY"), QStringLiteral("God Rays")},
        {QStringLiteral("INNR"), QStringLiteral("Instance Naming Rules")},
        {QStringLiteral("KSSM"), QStringLiteral("Sound Keyword Mapping")},
        {QStringLiteral("LAYR"), QStringLiteral("Layer")},
        {QStringLiteral("LENS"), QStringLiteral("Lens Flare")},
        {QStringLiteral("NOCM"), QStringLiteral("Navigation Mesh Obstacle Manager")},
        {QStringLiteral("OMOD"), QStringLiteral("Object Modification")},
        {QStringLiteral("PKIN"), QStringLiteral("Pack-In")},
        {QStringLiteral("RFGP"), QStringLiteral("Reference Group")},
        {QStringLiteral("SCCO"), QStringLiteral("Scene Collection")},
        {QStringLiteral("TERM"), QStringLiteral("Terminal")},
        {QStringLiteral("TRNS"), QStringLiteral("Transform")},
        {QStringLiteral("ZOOM"), QStringLiteral("Zoom")},
    };

    auto it = names.find(signature);
    if (it != names.end())
        return it.value();
    return signature;
}

} // namespace SignatureNames
