//! Code generator: converts parsed Delphi definitions into Rust source code
//! that constructs RecordDef / SubrecordDef / FieldDef values.

use crate::parser::*;

/// Generate Rust source code for all parsed records.
pub fn generate_all(records: &[ParsedRecord]) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by xedit_transpiler from Delphi .pas definitions.\n");
    out.push_str("// Do not edit manually.\n\n");
    out.push_str("use xedit_dom::Signature;\n");
    out.push_str("use xedit_dom::element::IntegerSize;\n");
    out.push_str("use crate::definition::{\n");
    out.push_str("    RecordDef, SubrecordDef, FieldDef, FieldType,\n");
    out.push_str("    FlagDef, EnumDef,\n");
    out.push_str("};\n\n");
    out.push_str("/// Register all parsed record definitions.\n");
    out.push_str("pub fn register_all() -> Vec<RecordDef> {\n");
    out.push_str("    vec![\n");

    for rec in records {
        out.push_str(&generate_record(rec, 2));
        out.push_str(",\n");
    }

    out.push_str("    ]\n");
    out.push_str("}\n");

    out
}

fn generate_record(rec: &ParsedRecord, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let mut out = format!("{pad}RecordDef {{\n");
    out.push_str(&format!(
        "{pad}    signature: Signature(*b\"{sig}\"),\n",
        sig = pad_signature(&rec.signature)
    ));
    out.push_str(&format!(
        "{pad}    name: \"{name}\".to_string(),\n",
        name = escape_rust_string(&rec.name)
    ));
    out.push_str(&format!("{pad}    members: vec![\n"));

    for member in &rec.members {
        let sub = generate_subrecord(member, indent + 2);
        out.push_str(&sub);
        out.push_str(",\n");
    }

    out.push_str(&format!("{pad}    ],\n"));
    out.push_str(&format!("{pad}}}"));
    out
}

fn generate_subrecord(node: &ParsedNode, indent: usize) -> String {
    let pad = "    ".repeat(indent);

    match node {
        ParsedNode::Struct { signature, name, fields } => {
            if let Some(sig) = signature {
                // A struct with a signature is a subrecord containing struct fields
                let mut out = format!("{pad}SubrecordDef {{\n");
                out.push_str(&format!(
                    "{pad}    signature: Signature(*b\"{sig}\"),\n",
                    sig = pad_signature(sig)
                ));
                out.push_str(&format!(
                    "{pad}    name: \"{name}\".to_string(),\n",
                    name = escape_rust_string(name)
                ));
                out.push_str(&format!("{pad}    fields: vec![\n"));
                for f in fields {
                    out.push_str(&generate_field(f, indent + 2));
                    out.push_str(",\n");
                }
                out.push_str(&format!("{pad}    ],\n"));
                out.push_str(&format!("{pad}    required: false,\n"));
                out.push_str(&format!("{pad}}}"));
                out
            } else {
                // Inline struct (no subrecord signature), wrap in a subrecord with empty sig
                let mut out = format!("{pad}SubrecordDef {{\n");
                out.push_str(&format!("{pad}    signature: Signature(*b\"    \"),\n"));
                out.push_str(&format!(
                    "{pad}    name: \"{name}\".to_string(),\n",
                    name = escape_rust_string(name)
                ));
                out.push_str(&format!("{pad}    fields: vec![\n"));
                for f in fields {
                    out.push_str(&generate_field(f, indent + 2));
                    out.push_str(",\n");
                }
                out.push_str(&format!("{pad}    ],\n"));
                out.push_str(&format!("{pad}    required: false,\n"));
                out.push_str(&format!("{pad}}}"));
                out
            }
        }

        ParsedNode::Integer { signature, name, int_type, format } => {
            generate_simple_subrecord(signature.as_deref(), name, &generate_integer_field_type(int_type, format), indent)
        }

        ParsedNode::Float { signature, name } => {
            generate_simple_subrecord(signature.as_deref(), name, "FieldType::Float", indent)
        }

        ParsedNode::String_ { signature, name, kind } => {
            let ft = match kind {
                StringKind::Normal => "FieldType::String",
                StringKind::Localized => "FieldType::String", // TODO: add LString variant
                StringKind::LenPrefixed => "FieldType::LenString",
            };
            generate_simple_subrecord(signature.as_deref(), name, ft, indent)
        }

        ParsedNode::FormId { signature, name, valid_refs } => {
            let refs_str = if valid_refs.is_empty() {
                "vec![]".to_string()
            } else {
                let items: Vec<String> = valid_refs.iter()
                    .map(|r| format!("Signature(*b\"{}\")", pad_signature(r)))
                    .collect();
                format!("vec![{}]", items.join(", "))
            };
            let ft = format!("FieldType::FormId {{ valid_refs: {} }}", refs_str);
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::ByteArray { signature, name, size } => {
            let ft = format!("FieldType::ByteArray {{ size: {} }}", size);
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::Empty { signature, name } => {
            generate_simple_subrecord(signature.as_deref(), name, "FieldType::ByteArray { size: 0 }", indent)
        }

        ParsedNode::Union { signature, name, members } => {
            let mut fields_str = String::new();
            for m in members {
                fields_str.push_str(&generate_field(m, indent + 2));
                fields_str.push_str(",\n");
            }
            let ft = format!(
                "FieldType::Union {{\n{pad}        members: vec![\n{fields}{pad}        ],\n{pad}    }}",
                pad = "    ".repeat(indent),
                fields = fields_str,
            );
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::Array { signature, name, element } => {
            let elem_field = generate_field_inline(element, indent + 2);
            let ft = format!(
                "FieldType::Array {{\n\
                 {pad}        name: \"{name}\".to_string(),\n\
                 {pad}        element: Box::new({elem}),\n\
                 {pad}        count: 0,\n\
                 {pad}    }}",
                pad = "    ".repeat(indent),
                name = escape_rust_string(name),
                elem = elem_field,
            );
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::VarRef { name } => {
            if let Some(resolved) = resolve_varref(name, &pad) {
                resolved
            } else {
                // Unresolved variable reference — keep TODO placeholder
                format!(
                    "{pad}// TODO: resolve variable reference: {name}\n\
                     {pad}SubrecordDef {{\n\
                     {pad}    signature: Signature(*b\"{sig}\"),\n\
                     {pad}    name: \"{name}\".to_string(),\n\
                     {pad}    fields: vec![],\n\
                     {pad}    required: false,\n\
                     {pad}}}",
                    pad = pad,
                    name = name,
                    sig = extract_sig_from_varref(name),
                )
            }
        }

        ParsedNode::Unused { size } => {
            format!(
                "{pad}SubrecordDef {{\n\
                 {pad}    signature: Signature(*b\"    \"),\n\
                 {pad}    name: \"Unused\".to_string(),\n\
                 {pad}    fields: vec![FieldDef {{ name: \"Unused\".to_string(), field_type: FieldType::ByteArray {{ size: {size} }} }}],\n\
                 {pad}    required: false,\n\
                 {pad}}}",
                pad = pad,
                size = size,
            )
        }

        ParsedNode::RStruct { name, members } => {
            // RStruct is like a group of subrecords -- emit them as a comment group
            let mut out = format!("{pad}// Begin RStruct: {name}\n", name = escape_rust_string(name));
            for (i, m) in members.iter().enumerate() {
                out.push_str(&generate_subrecord(m, indent));
                if i + 1 < members.len() {
                    out.push_str(",\n");
                }
            }
            // Note: the trailing comma from the caller handles the last one
            out
        }

        ParsedNode::RArray { name, element } => {
            // RArray is an array of subrecords -- emit the element as a subrecord
            let mut out = format!("{pad}// RArray: {name}\n", name = escape_rust_string(name));
            out.push_str(&generate_subrecord(element, indent));
            out
        }

        ParsedNode::Unrecognized { text, line_number } => {
            eprintln!("UNRECOGNIZED (line {}): {}", line_number, text);
            format!(
                "{pad}// UNRECOGNIZED (line {line}): {text}\n\
                 {pad}SubrecordDef {{\n\
                 {pad}    signature: Signature(*b\"    \"),\n\
                 {pad}    name: \"Unknown\".to_string(),\n\
                 {pad}    fields: vec![],\n\
                 {pad}    required: false,\n\
                 {pad}}}",
                pad = pad,
                line = line_number,
                text = escape_rust_string(&text.replace("\"", "\\\"").chars().take(80).collect::<String>()),
            )
        }
    }
}

/// Generate a FieldDef (for fields within a struct/union).
fn generate_field(node: &ParsedNode, indent: usize) -> String {
    let pad = "    ".repeat(indent);

    match node {
        ParsedNode::Integer { name, int_type, format, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: {ft} }}",
                name = escape_rust_string(name),
                ft = generate_integer_field_type(int_type, format),
            )
        }

        ParsedNode::Float { name, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Float }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::String_ { name, kind, .. } => {
            let ft = match kind {
                StringKind::Normal => "FieldType::String",
                StringKind::Localized => "FieldType::String",
                StringKind::LenPrefixed => "FieldType::LenString",
            };
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: {ft} }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::FormId { name, valid_refs, .. } => {
            let refs_str = if valid_refs.is_empty() {
                "vec![]".to_string()
            } else {
                let items: Vec<String> = valid_refs.iter()
                    .map(|r| format!("Signature(*b\"{}\")", pad_signature(r)))
                    .collect();
                format!("vec![{}]", items.join(", "))
            };
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::FormId {{ valid_refs: {refs} }} }}",
                name = escape_rust_string(name),
                refs = refs_str,
            )
        }

        ParsedNode::ByteArray { name, size, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::ByteArray {{ size: {size} }} }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::Unused { size } => {
            format!(
                "{pad}FieldDef {{ name: \"Unused\".to_string(), field_type: FieldType::ByteArray {{ size: {size} }} }}",
            )
        }

        ParsedNode::Empty { name, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::ByteArray {{ size: 0 }} }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::Struct { name, fields, .. } => {
            let mut inner = String::new();
            for f in fields {
                inner.push_str(&generate_field(f, indent + 1));
                inner.push_str(",\n");
            }
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Struct {{\n\
                 {pad}    name: \"{name}\".to_string(),\n\
                 {pad}    fields: vec![\n{inner}{pad}    ],\n\
                 {pad}}} }}",
                name = escape_rust_string(name),
                inner = inner,
            )
        }

        ParsedNode::Array { name, element, .. } => {
            let elem = generate_field_inline(element, indent + 1);
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Array {{\n\
                 {pad}    name: \"{name}\".to_string(),\n\
                 {pad}    element: Box::new({elem}),\n\
                 {pad}    count: 0,\n\
                 {pad}}} }}",
                name = escape_rust_string(name),
                elem = elem,
            )
        }

        ParsedNode::Union { name, members, .. } => {
            let mut inner = String::new();
            for m in members {
                inner.push_str(&generate_field(m, indent + 1));
                inner.push_str(",\n");
            }
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Union {{\n\
                 {pad}    members: vec![\n{inner}{pad}    ],\n\
                 {pad}}} }}",
                name = escape_rust_string(name),
                inner = inner,
            )
        }

        ParsedNode::VarRef { name } => {
            if let Some(resolved) = resolve_varref_field(name, &pad) {
                resolved
            } else {
                format!(
                    "{pad}// TODO: resolve variable reference: {name}\n\
                     {pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Unknown }}",
                    name = name,
                )
            }
        }

        ParsedNode::RStruct { name, .. } | ParsedNode::RArray { name, .. } => {
            format!(
                "{pad}// TODO: RStruct/RArray as field: {name}\n\
                 {pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Unknown }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::Unrecognized { text, line_number } => {
            eprintln!("UNRECOGNIZED field (line {}): {}", line_number, text);
            format!(
                "{pad}// UNRECOGNIZED (line {line}): {text}\n\
                 {pad}FieldDef {{ name: \"Unknown\".to_string(), field_type: FieldType::Unknown }}",
                line = line_number,
                text = text.chars().take(80).collect::<String>(),
            )
        }
    }
}

/// Generate a FieldDef as an inline expression (for array elements, etc.)
fn generate_field_inline(node: &ParsedNode, indent: usize) -> String {
    generate_field(node, indent)
}

fn generate_integer_field_type(int_type: &str, format: &Option<IntegerFormat>) -> String {
    let size = match int_type.trim() {
        "itU8" => "IntegerSize::U8",
        "itS8" => "IntegerSize::S8",
        "itU16" => "IntegerSize::U16",
        "itS16" => "IntegerSize::S16",
        "itU32" => "IntegerSize::U32",
        "itS32" => "IntegerSize::S32",
        "itU64" => "IntegerSize::U64",
        "itS64" => "IntegerSize::S64",
        _ => "IntegerSize::U32",
    };

    match format {
        Some(IntegerFormat::Flags(flags)) => {
            let items: Vec<String> = flags.iter()
                .map(|(idx, name)| {
                    let idx_val = idx.unwrap_or(0);
                    format!("({}, \"{}\".to_string())", idx_val, escape_rust_string(name))
                })
                .collect();
            format!(
                "FieldType::Integer {{ size: {}, enum_def: None, flags_def: Some(FlagDef {{ flags: vec![{}] }}) }}",
                size,
                items.join(", "),
            )
        }
        Some(IntegerFormat::Enum(values)) => {
            let items: Vec<String> = values.iter()
                .map(|(idx, name)| {
                    let idx_val = idx.unwrap_or(0);
                    format!("({}, \"{}\".to_string())", idx_val, escape_rust_string(name))
                })
                .collect();
            format!(
                "FieldType::Integer {{ size: {}, enum_def: Some(EnumDef {{ values: vec![{}] }}), flags_def: None }}",
                size,
                items.join(", "),
            )
        }
        Some(IntegerFormat::EnumNamed(name)) => {
            format!(
                "FieldType::Integer {{ size: {}, enum_def: None, flags_def: None }} /* TODO: {} */",
                size, name,
            )
        }
        None => {
            format!(
                "FieldType::Integer {{ size: {}, enum_def: None, flags_def: None }}",
                size,
            )
        }
    }
}

fn generate_simple_subrecord(sig: Option<&str>, name: &str, field_type: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let sig_str = sig.map(|s| pad_signature(s)).unwrap_or_else(|| "    ".to_string());
    format!(
        "{pad}SubrecordDef {{\n\
         {pad}    signature: Signature(*b\"{sig}\"),\n\
         {pad}    name: \"{name}\".to_string(),\n\
         {pad}    fields: vec![FieldDef {{ name: \"{name}\".to_string(), field_type: {ft} }}],\n\
         {pad}    required: false,\n\
         {pad}}}",
        pad = pad,
        sig = sig_str,
        name = escape_rust_string(name),
        ft = field_type,
    )
}

/// Pad a signature to exactly 4 chars for Signature(*b"XXXX").
fn pad_signature(sig: &str) -> String {
    let s = sig.trim();
    if s.len() >= 4 {
        s[..4].to_string()
    } else {
        format!("{:4}", s)
    }
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Resolve a VarRef name to a complete SubrecordDef code string.
/// Returns `None` if the variable is not in the known lookup table.
fn resolve_varref(name: &str, pad: &str) -> Option<String> {
    // Look up the resolved definition: (signature, display_name, fields_code)
    let (sig, display_name, fields_code) = resolve_varref_parts(name)?;

    Some(format!(
        "{pad}SubrecordDef {{\n\
         {pad}    signature: Signature(*b\"{sig}\"),\n\
         {pad}    name: \"{display_name}\".to_string(),\n\
         {pad}    fields: vec![{fields}],\n\
         {pad}    required: false,\n\
         {pad}}}",
        pad = pad,
        sig = pad_signature(sig),
        display_name = escape_rust_string(display_name),
        fields = fields_code,
    ))
}

/// Resolve a VarRef name to a FieldDef code string (for use inside structs/unions).
/// Returns `None` if the variable is not in the known lookup table.
fn resolve_varref_field(name: &str, pad: &str) -> Option<String> {
    let (_sig, display_name, _fields_code) = resolve_varref_parts(name)?;

    // Try to get a simple field type first
    if let Some(field_type) = resolve_varref_field_type(name) {
        return Some(format!(
            "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: {ft} }}",
            pad = pad,
            name = escape_rust_string(display_name),
            ft = field_type,
        ));
    }

    // For struct-based types, emit the full FieldDef from parts
    // The fields_code from resolve_varref_parts is already a complete FieldDef string
    let (_sig, _display_name, fields_code) = resolve_varref_parts(name)?;
    Some(format!("{pad}{fields}", pad = pad, fields = fields_code))
}

/// Returns (signature, display_name, fields_vec_contents) for known variable references.
fn resolve_varref_parts(name: &str) -> Option<(&'static str, &'static str, String)> {
    match name {
        // Editor ID - string
        "wbEDID" => Some(("EDID", "Editor ID",
            "FieldDef { name: \"Editor ID\".to_string(), field_type: FieldType::String }".into())),

        // Display name - localized string
        "wbFULL" | "wbFULLReq" => Some(("FULL", "Name",
            "FieldDef { name: \"Name\".to_string(), field_type: FieldType::String }".into())),

        // Description
        "wbDESC" | "wbDESCReq" => Some(("DESC", "Description",
            "FieldDef { name: \"Description\".to_string(), field_type: FieldType::String }".into())),

        // Object bounds - struct with 6 x S16
        "wbOBND" | "wbOBNDReq" => Some(("OBND", "Object Bounds", format!(
            "FieldDef {{ name: \"Object Bounds\".to_string(), field_type: FieldType::Struct {{\
             name: \"Object Bounds\".to_string(), fields: vec![\
             FieldDef {{ name: \"X1\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::S16, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"Y1\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::S16, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"Z1\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::S16, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"X2\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::S16, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"Y2\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::S16, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"Z2\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::S16, enum_def: None, flags_def: None }} }}\
             ] }} }}"))),

        // Model path
        "wbGenericModel" | "wbMODL" => Some(("MODL", "Model",
            "FieldDef { name: \"Model\".to_string(), field_type: FieldType::String }".into())),

        // Icon paths
        "wbICON" | "wbICONReq" => Some(("ICON", "Icon",
            "FieldDef { name: \"Icon\".to_string(), field_type: FieldType::String }".into())),

        "wbMICO" => Some(("MICO", "Menu Icon",
            "FieldDef { name: \"Menu Icon\".to_string(), field_type: FieldType::String }".into())),

        // Keywords
        "wbKeywords" => Some(("KSIZ", "Keywords",
            "FieldDef { name: \"Keywords\".to_string(), field_type: FieldType::ByteArray { size: 0 } }".into())),

        // VM adapter data
        "wbVMAD" | "wbVMADFragmentedSCPT" | "wbVMADFragmentedPERK"
        | "wbVMADFragmentedQUST" | "wbVMADFragmentedSCEN"
        | "wbVMADFragmentedINFO" | "wbVMADFragmentedPACK" => Some(("VMAD", "VM Adapter",
            "FieldDef { name: \"VM Adapter\".to_string(), field_type: FieldType::ByteArray { size: 0 } }".into())),

        // Color types - struct with R,G,B,A as U8
        "wbByteColors" | "wbByteRGBA" => Some(("    ", "Color", format!(
            "FieldDef {{ name: \"Color\".to_string(), field_type: FieldType::Struct {{\
             name: \"Color\".to_string(), fields: vec![\
             FieldDef {{ name: \"Red\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::U8, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"Green\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::U8, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"Blue\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::U8, enum_def: None, flags_def: None }} }},\
             FieldDef {{ name: \"Alpha\".to_string(), field_type: FieldType::Integer {{ size: IntegerSize::U8, enum_def: None, flags_def: None }} }}\
             ] }} }}"))),

        // Float color - struct with R,G,B,A as Float
        "wbFloatColors" => Some(("    ", "Color", format!(
            "FieldDef {{ name: \"Color\".to_string(), field_type: FieldType::Struct {{\
             name: \"Color\".to_string(), fields: vec![\
             FieldDef {{ name: \"Red\".to_string(), field_type: FieldType::Float }},\
             FieldDef {{ name: \"Green\".to_string(), field_type: FieldType::Float }},\
             FieldDef {{ name: \"Blue\".to_string(), field_type: FieldType::Float }},\
             FieldDef {{ name: \"Alpha\".to_string(), field_type: FieldType::Float }}\
             ] }} }}"))),

        // Boolean enum
        "wbBoolEnum" => Some(("    ", "Value",
            "FieldDef { name: \"Value\".to_string(), field_type: FieldType::Integer { size: IntegerSize::U8, enum_def: Some(EnumDef { values: vec![(0, \"False\".to_string()), (1, \"True\".to_string())] }), flags_def: None } }".into())),

        // Pickup sound
        "wbYNAM" => Some(("YNAM", "Pickup Sound",
            "FieldDef { name: \"Pickup Sound\".to_string(), field_type: FieldType::FormId { valid_refs: vec![Signature(*b\"SNDR\")] } }".into())),

        // Putdown sound
        "wbZNAM" => Some(("ZNAM", "Putdown Sound",
            "FieldDef { name: \"Putdown Sound\".to_string(), field_type: FieldType::FormId { valid_refs: vec![Signature(*b\"SNDR\")] } }".into())),

        // Equip type
        "wbETYP" | "wbETYPReq" => Some(("ETYP", "Equip Type",
            "FieldDef { name: \"Equip Type\".to_string(), field_type: FieldType::FormId { valid_refs: vec![Signature(*b\"EQUP\")] } }".into())),

        // Destructible
        "wbDEST" | "wbDESTActor" => Some(("DEST", "Destructible",
            "FieldDef { name: \"Destructible\".to_string(), field_type: FieldType::ByteArray { size: 0 } }".into())),

        // Conditions
        "wbConditions" | "wbCTDA" => Some(("CTDA", "Conditions",
            "FieldDef { name: \"Conditions\".to_string(), field_type: FieldType::ByteArray { size: 0 } }".into())),

        // Magic effects
        "wbEffects" | "wbEffectsReq" => Some(("EFID", "Effects",
            "FieldDef { name: \"Effects\".to_string(), field_type: FieldType::ByteArray { size: 0 } }".into())),

        _ => None,
    }
}

/// Returns just the FieldType code string for a known VarRef (used for field-level resolution).
fn resolve_varref_field_type(name: &str) -> Option<&'static str> {
    match name {
        "wbEDID" => Some("FieldType::String"),
        "wbFULL" | "wbFULLReq" => Some("FieldType::String"),
        "wbDESC" | "wbDESCReq" => Some("FieldType::String"),
        "wbGenericModel" | "wbMODL" => Some("FieldType::String"),
        "wbICON" | "wbICONReq" => Some("FieldType::String"),
        "wbMICO" => Some("FieldType::String"),
        "wbKeywords" => Some("FieldType::ByteArray { size: 0 }"),
        "wbVMAD" | "wbVMADFragmentedSCPT" | "wbVMADFragmentedPERK"
        | "wbVMADFragmentedQUST" | "wbVMADFragmentedSCEN"
        | "wbVMADFragmentedINFO" | "wbVMADFragmentedPACK" => Some("FieldType::ByteArray { size: 0 }"),
        "wbDEST" | "wbDESTActor" => Some("FieldType::ByteArray { size: 0 }"),
        "wbConditions" | "wbCTDA" => Some("FieldType::ByteArray { size: 0 }"),
        "wbEffects" | "wbEffectsReq" => Some("FieldType::ByteArray { size: 0 }"),
        "wbYNAM" => Some("FieldType::FormId { valid_refs: vec![Signature(*b\"SNDR\")] }"),
        "wbZNAM" => Some("FieldType::FormId { valid_refs: vec![Signature(*b\"SNDR\")] }"),
        "wbETYP" | "wbETYPReq" => Some("FieldType::FormId { valid_refs: vec![Signature(*b\"EQUP\")] }"),
        // For struct types (OBND, colors) we can't return a simple static str,
        // so fall back to Unknown for field-level usage (these are rare as fields)
        "wbOBND" | "wbOBNDReq" | "wbByteColors" | "wbByteRGBA"
        | "wbFloatColors" | "wbBoolEnum" => None,
        _ => None,
    }
}

/// Try to extract a 4-char signature from a variable reference name.
/// e.g., wbEDID -> EDID, wbFULL -> FULL
fn extract_sig_from_varref(name: &str) -> String {
    if name.len() >= 6 && name.starts_with("wb") {
        let rest = &name[2..];
        if rest.len() == 4 && rest.chars().all(|c| c.is_ascii_uppercase() || c.is_ascii_digit()) {
            return rest.to_string();
        }
    }
    "    ".to_string()
}
