//! Code generator: converts parsed Delphi definitions into Rust source code
//! that constructs RecordDef / SubrecordDef / FieldDef values.

use crate::parser::*;

/// Generate Rust source code for all parsed records.
pub fn generate_all(records: &[ParsedRecord]) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by xedit_transpiler from Delphi .pas definitions.\n");
    out.push_str("// Do not edit manually.\n\n");
    out.push_str("use xedit_dom::Signature;\n");
    out.push_str("use xedit_dom::element::IntegerSize;\n");
    out.push_str("use crate::definition::{\n");
    out.push_str("    RecordDef, SubrecordDef, FieldDef, FieldType,\n");
    out.push_str("    FlagDef, EnumDef,\n");
    out.push_str("};\n\n");
    out.push_str("/// Register all parsed record definitions.\n");
    out.push_str("pub fn register_all() -> Vec<RecordDef> {\n");
    out.push_str("    vec![\n");

    for rec in records {
        out.push_str(&generate_record(rec, 2));
        out.push_str(",\n");
    }

    out.push_str("    ]\n");
    out.push_str("}\n");

    out
}

fn generate_record(rec: &ParsedRecord, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let mut out = format!("{pad}RecordDef {{\n");
    out.push_str(&format!(
        "{pad}    signature: Signature(*b\"{sig}\"),\n",
        sig = pad_signature(&rec.signature)
    ));
    out.push_str(&format!(
        "{pad}    name: \"{name}\".to_string(),\n",
        name = escape_rust_string(&rec.name)
    ));
    out.push_str(&format!("{pad}    members: vec![\n"));

    for member in &rec.members {
        let sub = generate_subrecord(member, indent + 2);
        out.push_str(&sub);
        out.push_str(",\n");
    }

    out.push_str(&format!("{pad}    ],\n"));
    out.push_str(&format!("{pad}}}"));
    out
}

fn generate_subrecord(node: &ParsedNode, indent: usize) -> String {
    let pad = "    ".repeat(indent);

    match node {
        ParsedNode::Struct { signature, name, fields } => {
            if let Some(sig) = signature {
                // A struct with a signature is a subrecord containing struct fields
                let mut out = format!("{pad}SubrecordDef {{\n");
                out.push_str(&format!(
                    "{pad}    signature: Signature(*b\"{sig}\"),\n",
                    sig = pad_signature(sig)
                ));
                out.push_str(&format!(
                    "{pad}    name: \"{name}\".to_string(),\n",
                    name = escape_rust_string(name)
                ));
                out.push_str(&format!("{pad}    fields: vec![\n"));
                for f in fields {
                    out.push_str(&generate_field(f, indent + 2));
                    out.push_str(",\n");
                }
                out.push_str(&format!("{pad}    ],\n"));
                out.push_str(&format!("{pad}    required: false,\n"));
                out.push_str(&format!("{pad}}}"));
                out
            } else {
                // Inline struct (no subrecord signature), wrap in a subrecord with empty sig
                let mut out = format!("{pad}SubrecordDef {{\n");
                out.push_str(&format!("{pad}    signature: Signature(*b\"    \"),\n"));
                out.push_str(&format!(
                    "{pad}    name: \"{name}\".to_string(),\n",
                    name = escape_rust_string(name)
                ));
                out.push_str(&format!("{pad}    fields: vec![\n"));
                for f in fields {
                    out.push_str(&generate_field(f, indent + 2));
                    out.push_str(",\n");
                }
                out.push_str(&format!("{pad}    ],\n"));
                out.push_str(&format!("{pad}    required: false,\n"));
                out.push_str(&format!("{pad}}}"));
                out
            }
        }

        ParsedNode::Integer { signature, name, int_type, format } => {
            generate_simple_subrecord(signature.as_deref(), name, &generate_integer_field_type(int_type, format), indent)
        }

        ParsedNode::Float { signature, name } => {
            generate_simple_subrecord(signature.as_deref(), name, "FieldType::Float", indent)
        }

        ParsedNode::String_ { signature, name, kind } => {
            let ft = match kind {
                StringKind::Normal => "FieldType::String",
                StringKind::Localized => "FieldType::String", // TODO: add LString variant
                StringKind::LenPrefixed => "FieldType::LenString",
            };
            generate_simple_subrecord(signature.as_deref(), name, ft, indent)
        }

        ParsedNode::FormId { signature, name, valid_refs } => {
            let refs_str = if valid_refs.is_empty() {
                "vec![]".to_string()
            } else {
                let items: Vec<String> = valid_refs.iter()
                    .map(|r| format!("Signature(*b\"{}\")", pad_signature(r)))
                    .collect();
                format!("vec![{}]", items.join(", "))
            };
            let ft = format!("FieldType::FormId {{ valid_refs: {} }}", refs_str);
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::ByteArray { signature, name, size } => {
            let ft = format!("FieldType::ByteArray {{ size: {} }}", size);
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::Empty { signature, name } => {
            generate_simple_subrecord(signature.as_deref(), name, "FieldType::ByteArray { size: 0 }", indent)
        }

        ParsedNode::Union { signature, name, members } => {
            let mut fields_str = String::new();
            for m in members {
                fields_str.push_str(&generate_field(m, indent + 2));
                fields_str.push_str(",\n");
            }
            let ft = format!(
                "FieldType::Union {{\n{pad}        members: vec![\n{fields}{pad}        ],\n{pad}    }}",
                pad = "    ".repeat(indent),
                fields = fields_str,
            );
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::Array { signature, name, element } => {
            let elem_field = generate_field_inline(element, indent + 2);
            let ft = format!(
                "FieldType::Array {{\n\
                 {pad}        name: \"{name}\".to_string(),\n\
                 {pad}        element: Box::new({elem}),\n\
                 {pad}        count: 0,\n\
                 {pad}    }}",
                pad = "    ".repeat(indent),
                name = escape_rust_string(name),
                elem = elem_field,
            );
            generate_simple_subrecord(signature.as_deref(), name, &ft, indent)
        }

        ParsedNode::VarRef { name } => {
            // Generate a placeholder subrecord referencing the predefined variable
            format!(
                "{pad}// TODO: resolve variable reference: {name}\n\
                 {pad}SubrecordDef {{\n\
                 {pad}    signature: Signature(*b\"{sig}\"),\n\
                 {pad}    name: \"{name}\".to_string(),\n\
                 {pad}    fields: vec![],\n\
                 {pad}    required: false,\n\
                 {pad}}}",
                pad = pad,
                name = name,
                sig = extract_sig_from_varref(name),
            )
        }

        ParsedNode::Unused { size } => {
            format!(
                "{pad}SubrecordDef {{\n\
                 {pad}    signature: Signature(*b\"    \"),\n\
                 {pad}    name: \"Unused\".to_string(),\n\
                 {pad}    fields: vec![FieldDef {{ name: \"Unused\".to_string(), field_type: FieldType::ByteArray {{ size: {size} }} }}],\n\
                 {pad}    required: false,\n\
                 {pad}}}",
                pad = pad,
                size = size,
            )
        }

        ParsedNode::RStruct { name, members } => {
            // RStruct is like a group of subrecords -- emit them as a comment group
            let mut out = format!("{pad}// Begin RStruct: {name}\n", name = escape_rust_string(name));
            for (i, m) in members.iter().enumerate() {
                out.push_str(&generate_subrecord(m, indent));
                if i + 1 < members.len() {
                    out.push_str(",\n");
                }
            }
            // Note: the trailing comma from the caller handles the last one
            out
        }

        ParsedNode::RArray { name, element } => {
            // RArray is an array of subrecords -- emit the element as a subrecord
            let mut out = format!("{pad}// RArray: {name}\n", name = escape_rust_string(name));
            out.push_str(&generate_subrecord(element, indent));
            out
        }

        ParsedNode::Unrecognized { text, line_number } => {
            eprintln!("UNRECOGNIZED (line {}): {}", line_number, text);
            format!(
                "{pad}// UNRECOGNIZED (line {line}): {text}\n\
                 {pad}SubrecordDef {{\n\
                 {pad}    signature: Signature(*b\"    \"),\n\
                 {pad}    name: \"Unknown\".to_string(),\n\
                 {pad}    fields: vec![],\n\
                 {pad}    required: false,\n\
                 {pad}}}",
                pad = pad,
                line = line_number,
                text = escape_rust_string(&text.replace("\"", "\\\"").chars().take(80).collect::<String>()),
            )
        }
    }
}

/// Generate a FieldDef (for fields within a struct/union).
fn generate_field(node: &ParsedNode, indent: usize) -> String {
    let pad = "    ".repeat(indent);

    match node {
        ParsedNode::Integer { name, int_type, format, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: {ft} }}",
                name = escape_rust_string(name),
                ft = generate_integer_field_type(int_type, format),
            )
        }

        ParsedNode::Float { name, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Float }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::String_ { name, kind, .. } => {
            let ft = match kind {
                StringKind::Normal => "FieldType::String",
                StringKind::Localized => "FieldType::String",
                StringKind::LenPrefixed => "FieldType::LenString",
            };
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: {ft} }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::FormId { name, valid_refs, .. } => {
            let refs_str = if valid_refs.is_empty() {
                "vec![]".to_string()
            } else {
                let items: Vec<String> = valid_refs.iter()
                    .map(|r| format!("Signature(*b\"{}\")", pad_signature(r)))
                    .collect();
                format!("vec![{}]", items.join(", "))
            };
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::FormId {{ valid_refs: {refs} }} }}",
                name = escape_rust_string(name),
                refs = refs_str,
            )
        }

        ParsedNode::ByteArray { name, size, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::ByteArray {{ size: {size} }} }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::Unused { size } => {
            format!(
                "{pad}FieldDef {{ name: \"Unused\".to_string(), field_type: FieldType::ByteArray {{ size: {size} }} }}",
            )
        }

        ParsedNode::Empty { name, .. } => {
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::ByteArray {{ size: 0 }} }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::Struct { name, fields, .. } => {
            let mut inner = String::new();
            for f in fields {
                inner.push_str(&generate_field(f, indent + 1));
                inner.push_str(",\n");
            }
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Struct {{\n\
                 {pad}    name: \"{name}\".to_string(),\n\
                 {pad}    fields: vec![\n{inner}{pad}    ],\n\
                 {pad}}} }}",
                name = escape_rust_string(name),
                inner = inner,
            )
        }

        ParsedNode::Array { name, element, .. } => {
            let elem = generate_field_inline(element, indent + 1);
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Array {{\n\
                 {pad}    name: \"{name}\".to_string(),\n\
                 {pad}    element: Box::new({elem}),\n\
                 {pad}    count: 0,\n\
                 {pad}}} }}",
                name = escape_rust_string(name),
                elem = elem,
            )
        }

        ParsedNode::Union { name, members, .. } => {
            let mut inner = String::new();
            for m in members {
                inner.push_str(&generate_field(m, indent + 1));
                inner.push_str(",\n");
            }
            format!(
                "{pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Union {{\n\
                 {pad}    members: vec![\n{inner}{pad}    ],\n\
                 {pad}}} }}",
                name = escape_rust_string(name),
                inner = inner,
            )
        }

        ParsedNode::VarRef { name } => {
            format!(
                "{pad}// TODO: resolve variable reference: {name}\n\
                 {pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Unknown }}",
                name = name,
            )
        }

        ParsedNode::RStruct { name, .. } | ParsedNode::RArray { name, .. } => {
            format!(
                "{pad}// TODO: RStruct/RArray as field: {name}\n\
                 {pad}FieldDef {{ name: \"{name}\".to_string(), field_type: FieldType::Unknown }}",
                name = escape_rust_string(name),
            )
        }

        ParsedNode::Unrecognized { text, line_number } => {
            eprintln!("UNRECOGNIZED field (line {}): {}", line_number, text);
            format!(
                "{pad}// UNRECOGNIZED (line {line}): {text}\n\
                 {pad}FieldDef {{ name: \"Unknown\".to_string(), field_type: FieldType::Unknown }}",
                line = line_number,
                text = text.chars().take(80).collect::<String>(),
            )
        }
    }
}

/// Generate a FieldDef as an inline expression (for array elements, etc.)
fn generate_field_inline(node: &ParsedNode, indent: usize) -> String {
    generate_field(node, indent)
}

fn generate_integer_field_type(int_type: &str, format: &Option<IntegerFormat>) -> String {
    let size = match int_type.trim() {
        "itU8" => "IntegerSize::U8",
        "itS8" => "IntegerSize::S8",
        "itU16" => "IntegerSize::U16",
        "itS16" => "IntegerSize::S16",
        "itU32" => "IntegerSize::U32",
        "itS32" => "IntegerSize::S32",
        "itU64" => "IntegerSize::U64",
        "itS64" => "IntegerSize::S64",
        _ => "IntegerSize::U32",
    };

    match format {
        Some(IntegerFormat::Flags(flags)) => {
            let items: Vec<String> = flags.iter()
                .map(|(idx, name)| {
                    let idx_val = idx.unwrap_or(0);
                    format!("({}, \"{}\".to_string())", idx_val, escape_rust_string(name))
                })
                .collect();
            format!(
                "FieldType::Integer {{ size: {}, enum_def: None, flags_def: Some(FlagDef {{ flags: vec![{}] }}) }}",
                size,
                items.join(", "),
            )
        }
        Some(IntegerFormat::Enum(values)) => {
            let items: Vec<String> = values.iter()
                .map(|(idx, name)| {
                    let idx_val = idx.unwrap_or(0);
                    format!("({}, \"{}\".to_string())", idx_val, escape_rust_string(name))
                })
                .collect();
            format!(
                "FieldType::Integer {{ size: {}, enum_def: Some(EnumDef {{ values: vec![{}] }}), flags_def: None }}",
                size,
                items.join(", "),
            )
        }
        Some(IntegerFormat::EnumNamed(name)) => {
            format!(
                "FieldType::Integer {{ size: {}, enum_def: None, flags_def: None }} /* TODO: {} */",
                size, name,
            )
        }
        None => {
            format!(
                "FieldType::Integer {{ size: {}, enum_def: None, flags_def: None }}",
                size,
            )
        }
    }
}

fn generate_simple_subrecord(sig: Option<&str>, name: &str, field_type: &str, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let sig_str = sig.map(|s| pad_signature(s)).unwrap_or_else(|| "    ".to_string());
    format!(
        "{pad}SubrecordDef {{\n\
         {pad}    signature: Signature(*b\"{sig}\"),\n\
         {pad}    name: \"{name}\".to_string(),\n\
         {pad}    fields: vec![FieldDef {{ name: \"{name}\".to_string(), field_type: {ft} }}],\n\
         {pad}    required: false,\n\
         {pad}}}",
        pad = pad,
        sig = sig_str,
        name = escape_rust_string(name),
        ft = field_type,
    )
}

/// Pad a signature to exactly 4 chars for Signature(*b"XXXX").
fn pad_signature(sig: &str) -> String {
    let s = sig.trim();
    if s.len() >= 4 {
        s[..4].to_string()
    } else {
        format!("{:4}", s)
    }
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Try to extract a 4-char signature from a variable reference name.
/// e.g., wbEDID -> EDID, wbFULL -> FULL
fn extract_sig_from_varref(name: &str) -> String {
    if name.len() >= 6 && name.starts_with("wb") {
        let rest = &name[2..];
        if rest.len() == 4 && rest.chars().all(|c| c.is_ascii_uppercase() || c.is_ascii_digit()) {
            return rest.to_string();
        }
    }
    "    ".to_string()
}
